#!/bin/bash

# Deploy the blue version
echo "deploying blue environment..."
kubectl apply -f blue_deployment.yaml

# 2 deploy the green version
echo "deploying green environment..."
kubectl apply -f green_deployment.yaml

#3 wait for green pods to be ready
echo "Waiting for green pods to initialize..."
sleep 10

# 4 check logs for the green version to ensure no errors
echo "Checking logs for green  pods ..."
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD

# 5 apply the service 
echo "Applying service configuration..."
kubectl apply -f kubeservice.yaml

echo "Blue and green are both running. To switch traffic, update version to 'green' in kubeservice.yaml and re-apply."
